name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Go for use with actions
      uses: actions/setup-go@v1.0.0
      with:
        version: 1.13
    - name: Install goimports
      run: go get golang.org/x/tools/cmd/goimports
    - name: Run goimports check
      run: test -z "`for d in $GO_USR_DIRS; do goimports -d $d/*.go | tee /dev/stderr; done`"
      env:
        GO_USR_DIRS: $(go list -f {{.Dir}} ./... | grep -E -v "/gen-go/|/vendor/")
    - name: Create aurora/mesos docker cluster
      run: docker-compose up -d
    - name: Run tests
      run: go test -race -coverprofile=coverage.txt -covermode=atomic -v github.com/aurora-scheduler/gorealis/v2
        
